# Set the build language to Python
language: python

# Set the python version to 3.5
python:
  - "3.6"

# Install the codecov pip dependency
install:
  - pip install git+https://github.com/UBC-MDS/explorePy.git
  - pip install -U pytest pytest-cov
  - pip install pandas
  - pip install codecov

# Run the unit test
script:
  #- cd explorePy/tests
  - pytest --cov=./
# Push the results back to codecov
after_success:
  - codecov
